//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmWeb_30.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public long IdSeguridad { get; set; }
        public string Nombre { get; set; }
        public string CodigoUsuario { get; set; }
        public string Contraseña { get; set; }
        public string Rol { get; set; }
    }
}
