//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmWeb_30.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBIAUnidadTrabajoPersonas
    {
        public long IdEmpresa { get; set; }
        public long IdUnidadTrabajo { get; set; }
        public long IdUnidadTrabajoProceso { get; set; }
        public long IdUnidadPersona { get; set; }
        public long IdClienteProceso { get; set; }
        public string Nombre { get; set; }
        public long IdDocumentoBIA { get; set; }
        public long IdProceso { get; set; }
    
        public virtual tblBIAClienteProceso tblBIAClienteProceso { get; set; }
        public virtual tblBIAUnidadTrabajoProceso tblBIAUnidadTrabajoProceso { get; set; }
    }
}
