//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmWeb_30.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumentoCertificacion
    {
        public long IdEmpresa { get; set; }
        public long IdDocumento { get; set; }
        public long IdTipoDocumento { get; set; }
        public long IdCertificacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<long> IdPersona { get; set; }
        public bool Procesado { get; set; }
        public Nullable<bool> Certificado { get; set; }
    
        public virtual tblDocumento tblDocumento { get; set; }
        public virtual tblPersona tblPersona { get; set; }
    }
}
