//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmWeb_30.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpresa()
        {
            this.tblAuditoria = new HashSet<tblAuditoria>();
            this.tblAuditoriaProcesoCritico = new HashSet<tblAuditoriaProcesoCritico>();
            this.tblBCPDocumento = new HashSet<tblBCPDocumento>();
            this.tblBIACadenaServicio = new HashSet<tblBIACadenaServicio>();
            this.tblBIADocumento = new HashSet<tblBIADocumento>();
            this.tblBIAUnidadTrabajo = new HashSet<tblBIAUnidadTrabajo>();
            this.tblCargo = new HashSet<tblCargo>();
            this.tblCriticidad = new HashSet<tblCriticidad>();
            this.tblDispositivoConexion = new HashSet<tblDispositivoConexion>();
            this.tblDispositivoConexion_old = new HashSet<tblDispositivoConexion_old>();
            this.tblDocumento = new HashSet<tblDocumento>();
            this.tblDocumentoPersonaClave = new HashSet<tblDocumentoPersonaClave>();
            this.tblProbabilidadRiesgo = new HashSet<tblProbabilidadRiesgo>();
            this.tblEscala = new HashSet<tblEscala>();
            this.tblLocalidad = new HashSet<tblLocalidad>();
            this.tblPersona = new HashSet<tblPersona>();
            this.tblProveedor = new HashSet<tblProveedor>();
            this.tblUnidadOrganizativa = new HashSet<tblUnidadOrganizativa>();
            this.tblVicepresidencia = new HashSet<tblVicepresidencia>();
            this.tblEmpresaModulo = new HashSet<tblEmpresaModulo>();
            this.tblEmpresaUsuario = new HashSet<tblEmpresaUsuario>();
            this.tblFormatosEmail = new HashSet<tblFormatosEmail>();
            this.tblIncidentes = new HashSet<tblIncidentes>();
            this.tblIniciativas_Anexo = new HashSet<tblIniciativas_Anexo>();
            this.tblIniciativas = new HashSet<tblIniciativas>();
            this.tblModulo_NivelUsuario = new HashSet<tblModulo_NivelUsuario>();
            this.tblModulo = new HashSet<tblModulo>();
            this.tblModuloAnexo = new HashSet<tblModuloAnexo>();
            this.tblPBEPruebaEjecucion = new HashSet<tblPBEPruebaEjecucion>();
            this.tblPBEPruebaEjecucionEjercicio = new HashSet<tblPBEPruebaEjecucionEjercicio>();
            this.tblPBEPruebaPlanificacion = new HashSet<tblPBEPruebaPlanificacion>();
            this.tblPlanTrabajo = new HashSet<tblPlanTrabajo>();
            this.tblPlanTrabajoAccion = new HashSet<tblPlanTrabajoAccion>();
            this.tblPMTMensajeActualizacion = new HashSet<tblPMTMensajeActualizacion>();
            this.tblPMTProgramacion = new HashSet<tblPMTProgramacion>();
            this.tblPMTResponsableUpdate = new HashSet<tblPMTResponsableUpdate>();
            this.tblProducto = new HashSet<tblProducto>();
            this.tblUsuarioUnidadOrganizativa = new HashSet<tblUsuarioUnidadOrganizativa>();
        }
    
        public long IdEmpresa { get; set; }
        public string NombreFiscal { get; set; }
        public string RegistroFiscal { get; set; }
        public string NombreComercial { get; set; }
        public string DireccionAdministrativa { get; set; }
        public long IdEstado { get; set; }
        public System.DateTime FechaUltimoEstado { get; set; }
        public string LogoURL { get; set; }
        public System.DateTime FechaInicioActividad { get; set; }
        public Nullable<bool> CrearProcesos { get; set; }
        public Nullable<bool> CrearUnidadOrganizativa { get; set; }
        public Nullable<bool> CrearUnidadTrabajo { get; set; }
        public Nullable<bool> CrearAplicaciones { get; set; }
        public Nullable<bool> CrearDocumento { get; set; }
        public Nullable<long> IdPais { get; set; }
        public Nullable<long> IdPaisEstado { get; set; }
        public Nullable<long> IdPaisEstadoCiudad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAuditoria> tblAuditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAuditoriaProcesoCritico> tblAuditoriaProcesoCritico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBCPDocumento> tblBCPDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBIACadenaServicio> tblBIACadenaServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBIADocumento> tblBIADocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBIAUnidadTrabajo> tblBIAUnidadTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCargo> tblCargo { get; set; }
        public virtual tblCiudad tblCiudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCriticidad> tblCriticidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDispositivoConexion> tblDispositivoConexion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDispositivoConexion_old> tblDispositivoConexion_old { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumento> tblDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentoPersonaClave> tblDocumentoPersonaClave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProbabilidadRiesgo> tblProbabilidadRiesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEscala> tblEscala { get; set; }
        public virtual tblEstado tblEstado { get; set; }
        public virtual tblEstadoEmpresa tblEstadoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLocalidad> tblLocalidad { get; set; }
        public virtual tblPais tblPais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersona> tblPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProveedor> tblProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUnidadOrganizativa> tblUnidadOrganizativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVicepresidencia> tblVicepresidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpresaModulo> tblEmpresaModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpresaUsuario> tblEmpresaUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFormatosEmail> tblFormatosEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIncidentes> tblIncidentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIniciativas_Anexo> tblIniciativas_Anexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIniciativas> tblIniciativas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblModulo_NivelUsuario> tblModulo_NivelUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblModulo> tblModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblModuloAnexo> tblModuloAnexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaEjecucion> tblPBEPruebaEjecucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaEjecucionEjercicio> tblPBEPruebaEjecucionEjercicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaPlanificacion> tblPBEPruebaPlanificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlanTrabajo> tblPlanTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlanTrabajoAccion> tblPlanTrabajoAccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPMTMensajeActualizacion> tblPMTMensajeActualizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPMTProgramacion> tblPMTProgramacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPMTResponsableUpdate> tblPMTResponsableUpdate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProducto> tblProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsuarioUnidadOrganizativa> tblUsuarioUnidadOrganizativa { get; set; }
    }
}
