//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmWeb_30.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIniciativas_Anexo
    {
        public long IdEmpresa { get; set; }
        public long IdIniciativa { get; set; }
        public long IdAnexo { get; set; }
        public string Nombre { get; set; }
        public string RutaArchivo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
    }
}
