//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmWeb_30.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlanTrabajoAuditoria
    {
        public long IdEmpresa { get; set; }
        public long IdAccion { get; set; }
        public long IdActividad { get; set; }
        public long IdCambioEstado { get; set; }
        public System.DateTime FechaCambioEstado { get; set; }
        public short Estado { get; set; }
        public long IdUsuarioCambioEstado { get; set; }
    
        public virtual tblPlanTrabajo tblPlanTrabajo { get; set; }
        public virtual tblPlanTrabajoAccion tblPlanTrabajoAccion { get; set; }
        public virtual tblPlanTrabajoEstatus tblPlanTrabajoEstatus { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
