//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmWeb_30.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuarioUnidadOrganizativa
    {
        public long IdEmpresa { get; set; }
        public long IdUnidadOrganizativa { get; set; }
        public long IdUsuario { get; set; }
        public long IdNivelUsuario { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblNivelUsuario tblNivelUsuario { get; set; }
        public virtual tblUnidadOrganizativa tblUnidadOrganizativa { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
