//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.AboutResource", typeof(AboutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre BcmWeb_30.net.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiar el flujo de producción e identificar los puntos críticos para la consecución de objetivos..
        /// </summary>
        public static string Lista01Elemento01 {
            get {
                return ResourceManager.GetString("Lista01Elemento01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar los controles actuales para minimizar dichos puntos críticos..
        /// </summary>
        public static string Lista01Elemento02 {
            get {
                return ResourceManager.GetString("Lista01Elemento02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificar las amenazas al negocio..
        /// </summary>
        public static string Lista02Elemento01 {
            get {
                return ResourceManager.GetString("Lista02Elemento01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer escenarios de siniestros y evaluar su impacto en la organización..
        /// </summary>
        public static string Lista02Elemento02 {
            get {
                return ResourceManager.GetString("Lista02Elemento02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiar el modo de restablecer las operaciones dentro del margen de tiempo requerido..
        /// </summary>
        public static string Lista03Elemento01 {
            get {
                return ResourceManager.GetString("Lista03Elemento01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificar los recursos, materiales e información necesarios para lograr el objetivo anterior..
        /// </summary>
        public static string Lista03Elemento02 {
            get {
                return ResourceManager.GetString("Lista03Elemento02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define las medidas a adoptar en el minuto 1 de la emergencia (llamar a los servicios de emergencia, efectuar la recuperación y salvamento de bienes, etc.)..
        /// </summary>
        public static string Lista04Elemento01 {
            get {
                return ResourceManager.GetString("Lista04Elemento01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llamadas en cascada a miembros estratégicos de la organización, comunicación eficaz con los medios de comunicación, aviso a clientes y proveedores..
        /// </summary>
        public static string Lista04Elemento02 {
            get {
                return ResourceManager.GetString("Lista04Elemento02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aseguran la validez y robustez del documento..
        /// </summary>
        public static string Lista05Elemento01 {
            get {
                return ResourceManager.GetString("Lista05Elemento01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe existir una revisión regular del plan para asegurar su puesta al día..
        /// </summary>
        public static string Lista05Elemento02 {
            get {
                return ResourceManager.GetString("Lista05Elemento02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aumenta la probabilidad de supervivencia de la empresa tras un siniestro..
        /// </summary>
        public static string Lista06Elemento01 {
            get {
                return ResourceManager.GetString("Lista06Elemento01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantiene o incluso mejora la reputación de la empresa..
        /// </summary>
        public static string Lista06Elemento02 {
            get {
                return ResourceManager.GetString("Lista06Elemento02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evita errores costosos, tanto antes como después del siniestro..
        /// </summary>
        public static string Lista06Elemento03 {
            get {
                return ResourceManager.GetString("Lista06Elemento03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimiza los recursos, canalizándolos allí donde resultan más útiles..
        /// </summary>
        public static string Lista06Elemento04 {
            get {
                return ResourceManager.GetString("Lista06Elemento04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de la Continuidad del Negocio (BCM)..
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es el Proceso o actividad de Gestionar el Riesgo que puede tener un alto impacto en el Negocio, para evitar o minimizar el riesgo en una interrupción que pueda impedir u obstaculizar que una Organización pueda alcanzar sus objetivos estratégicos, operacionales y de proyectos. BCM protege los intereses, la reputación, la marca y las actividades que aportan valor al Negocio. Los Procesos de BCM incluyen reducir el Riesgo a un nivel aceptable y planificar el restablecimiento de los Procesos de Negocio ante una [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Parrafo01 {
            get {
                return ResourceManager.GetString("Parrafo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso de Gestión de Continuidad de Negocios (Business Continuity Management-BCM) le permite a su organización estar preparada y responder ante eventos mayores, a través de Planes de Continuidad del Negocio (BCP), se pueden determinar los procesos críticos, y en base al resultado de los mismos, definir los procedimientos que le permita seguir operando con el mínimo de servicios acordados. Esta actividad debe ser llevada a cabo por los dueños y/o responsables de cada proceso crítico dentro de la organiza [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Parrafo02 {
            get {
                return ResourceManager.GetString("Parrafo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El BCM define el modo más efectivo de abordar las repercusiones inmediatas de un acontecimiento, para alcanzar la operación normal lo más rápidamente posible. No se trata de seguir lo que se dice en unas plantillas, sino de conocer la respuesta específica que requiere una organización dinámica, lo cual supone a menudo delegar autoridad y controlar las interferencias internas..
        /// </summary>
        public static string Parrafo03 {
            get {
                return ResourceManager.GetString("Parrafo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una crisis bien gestionada puede llegar a mejorar la reputación de la empresa, reforzar la moral de los trabajadores y hacer que la organización salga de la crisis más fuerte..
        /// </summary>
        public static string Parrafo04 {
            get {
                return ResourceManager.GetString("Parrafo04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para conseguir implantar un BCM en una organización, deben seguirse los siguientes pasos..
        /// </summary>
        public static string Parrafo05 {
            get {
                return ResourceManager.GetString("Parrafo05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los beneficios de realizar una metodología como la expuesta en los párrafos anteriores, pueden resumirse como sigue:.
        /// </summary>
        public static string Parrafo06 {
            get {
                return ResourceManager.GetString("Parrafo06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , es un sistema que le ayuda a manejar la Gestión de Continuidad de su Negocio, de forma interactiva, accesible desde cualquier lugar y a cualquier hora; a través de éste sistema usted podrá ingresar a la información de los procesos fundamentales del negocio con sus respectivos impactos, riesgos y controles, interdependencias, proveedores, documentación esencial, productos asociados, personal clave, entre otros; visualizar claramente cuáles de esos procesos son críticos para su Negocio y para éstos procesos [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Parrafo07 {
            get {
                return ResourceManager.GetString("Parrafo07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué puede suministrar el BCM?.
        /// </summary>
        public static string Pregunta01 {
            get {
                return ResourceManager.GetString("Pregunta01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cómo funciona un BCM?.
        /// </summary>
        public static string Pregunta02 {
            get {
                return ResourceManager.GetString("Pregunta02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cuáles son los beneficios de la implementación del BCM?.
        /// </summary>
        public static string Pregunta03 {
            get {
                return ResourceManager.GetString("Pregunta03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control y Evaluación del Riesgo..
        /// </summary>
        public static string Subtitulo01 {
            get {
                return ResourceManager.GetString("Subtitulo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis del Impacto en el Negocio..
        /// </summary>
        public static string Subtitulo02 {
            get {
                return ResourceManager.GetString("Subtitulo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollo de estrategias de continuidad..
        /// </summary>
        public static string Subtitulo03 {
            get {
                return ResourceManager.GetString("Subtitulo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Respuesta Inmediata y Gestión de Crisis..
        /// </summary>
        public static string Subtitulo04 {
            get {
                return ResourceManager.GetString("Subtitulo04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de los planes:.
        /// </summary>
        public static string Subtitulo05 {
            get {
                return ResourceManager.GetString("Subtitulo05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema para la Gestión de la Continuidad del Negocio.
        /// </summary>
        public static string Subtitulo06 {
            get {
                return ResourceManager.GetString("Subtitulo06", resourceCulture);
            }
        }
    }
}
