//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdministracionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministracionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.AdministracionResource", typeof(AdministracionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string botActualizar {
            get {
                return ResourceManager.GetString("botActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar.
        /// </summary>
        public static string captionBotonActivar {
            get {
                return ResourceManager.GetString("captionBotonActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear.
        /// </summary>
        public static string captionBotonBloquear {
            get {
                return ResourceManager.GetString("captionBotonBloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string captionBotonEditar {
            get {
                return ResourceManager.GetString("captionBotonEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string captionBotonEliminar {
            get {
                return ResourceManager.GetString("captionBotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string captionCiudad {
            get {
                return ResourceManager.GetString("captionCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del Módulo.
        /// </summary>
        public static string captionDescripcionModulo {
            get {
                return ResourceManager.GetString("captionDescripcionModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string captionDireccion {
            get {
                return ResourceManager.GetString("captionDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string captionEstado {
            get {
                return ResourceManager.GetString("captionEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string captionEstatus {
            get {
                return ResourceManager.GetString("captionEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde:.
        /// </summary>
        public static string captionFechaDesde {
            get {
                return ResourceManager.GetString("captionFechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta:.
        /// </summary>
        public static string captionFechaHasta {
            get {
                return ResourceManager.GetString("captionFechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Inicio de Actividades.
        /// </summary>
        public static string captionFechaInicio {
            get {
                return ResourceManager.GetString("captionFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Ingreso.
        /// </summary>
        public static string captionFechaRegistro {
            get {
                return ResourceManager.GetString("captionFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Último Estado.
        /// </summary>
        public static string captionFechaUltimoEstado {
            get {
                return ResourceManager.GetString("captionFechaUltimoEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logotipo.
        /// </summary>
        public static string captionLogo {
            get {
                return ResourceManager.GetString("captionLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos Permitidos.
        /// </summary>
        public static string captionModulos {
            get {
                return ResourceManager.GetString("captionModulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Comercial.
        /// </summary>
        public static string captionNombreComercial {
            get {
                return ResourceManager.GetString("captionNombreComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Fiscal.
        /// </summary>
        public static string captionNombreFiscal {
            get {
                return ResourceManager.GetString("captionNombreFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Módulo.
        /// </summary>
        public static string captionNombreModulo {
            get {
                return ResourceManager.GetString("captionNombreModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string captionPais {
            get {
                return ResourceManager.GetString("captionPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Registro Fiscal.
        /// </summary>
        public static string captionRegistroFiscal {
            get {
                return ResourceManager.GetString("captionRegistroFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string captionSelectModulo {
            get {
                return ResourceManager.GetString("captionSelectModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string captionUsuario {
            get {
                return ResourceManager.GetString("captionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro de activar la empresa {0}.
        /// </summary>
        public static string ConfirmActivarMessage {
            get {
                return ResourceManager.GetString("ConfirmActivarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro de bloquear la empresa {0}.
        /// </summary>
        public static string ConfirmBloquearMessage {
            get {
                return ResourceManager.GetString("ConfirmBloquearMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro de eliminar la empresa {0}.
        /// </summary>
        public static string ConfirmEliminarMessage {
            get {
                return ResourceManager.GetString("ConfirmEliminarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los Usuarios.
        /// </summary>
        public static string itemAllUsers {
            get {
                return ResourceManager.GetString("itemAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de la Empresa.
        /// </summary>
        public static string TitleEditEmpresa {
            get {
                return ResourceManager.GetString("TitleEditEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulos autorizados.
        /// </summary>
        public static string TitleEditModulos {
            get {
                return ResourceManager.GetString("TitleEditModulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Usuario.
        /// </summary>
        public static string TitleEditUsuario {
            get {
                return ResourceManager.GetString("TitleEditUsuario", resourceCulture);
            }
        }
    }
}
