//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BCMWebPublic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BCMWebPublic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.BCMWebPublic", typeof(BCMWebPublic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre BCMWeb.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexos.
        /// </summary>
        public static string botAnexosText {
            get {
                return ResourceManager.GetString("botAnexosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string botReturnText {
            get {
                return ResourceManager.GetString("botReturnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso desde dispositivos móviles.
        /// </summary>
        public static string BSMMovilPageTitle {
            get {
                return ResourceManager.GetString("BSMMovilPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificador de Mantenimientos.
        /// </summary>
        public static string captionBotonMantenimientos {
            get {
                return ResourceManager.GetString("captionBotonMantenimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string captionButtonCancel {
            get {
                return ResourceManager.GetString("captionButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string captionButtonDelete {
            get {
                return ResourceManager.GetString("captionButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string captionButtonEdit {
            get {
                return ResourceManager.GetString("captionButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string captionButtonEnviar {
            get {
                return ResourceManager.GetString("captionButtonEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        public static string captionButtonFilter {
            get {
                return ResourceManager.GetString("captionButtonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string captionButtonImprimir {
            get {
                return ResourceManager.GetString("captionButtonImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe Preliminar.
        /// </summary>
        public static string captionButtonInforme {
            get {
                return ResourceManager.GetString("captionButtonInforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string captionButtonNew {
            get {
                return ResourceManager.GetString("captionButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string captionButtonNext {
            get {
                return ResourceManager.GetString("captionButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidentes.
        /// </summary>
        public static string captionButtonPMI {
            get {
                return ResourceManager.GetString("captionButtonPMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificador de Pruebas.
        /// </summary>
        public static string captionButtonPPE {
            get {
                return ResourceManager.GetString("captionButtonPPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string captionButtonPrev {
            get {
                return ResourceManager.GetString("captionButtonPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string captionButtonSave {
            get {
                return ResourceManager.GetString("captionButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        public static string captionButtonUpload {
            get {
                return ResourceManager.GetString("captionButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string captionButtonVer {
            get {
                return ResourceManager.GetString("captionButtonVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Políticas de Confidencialidad.
        /// </summary>
        public static string ConfidencialidadPageTitle {
            get {
                return ResourceManager.GetString("ConfidencialidadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se perderá la información actualizada. ¿Desea continuar con la cancelación?.
        /// </summary>
        public static string ConfirmCancelMessage {
            get {
                return ResourceManager.GetString("ConfirmCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Realmente desea eliminar el documento {0}?.
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctenos.
        /// </summary>
        public static string ContactPageTitle {
            get {
                return ResourceManager.GetString("ContactPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información General.
        /// </summary>
        public static string FAQPageTitle {
            get {
                return ResourceManager.GetString("FAQPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realice su selección....
        /// </summary>
        public static string itemSelectValue {
            get {
                return ResourceManager.GetString("itemSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GESTOR DE PLANES DE CONTINUIDAD.
        /// </summary>
        public static string labelAppSlogan {
            get {
                return ResourceManager.GetString("labelAppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCMWeb.
        /// </summary>
        public static string labelAppTitle {
            get {
                return ResourceManager.GetString("labelAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando. Espere por favor....
        /// </summary>
        public static string labelLoadPanel {
            get {
                return ResourceManager.GetString("labelLoadPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviando correos a los aprobadores. Espere por favor....
        /// </summary>
        public static string labelLoadPanelAprobacion {
            get {
                return ResourceManager.GetString("labelLoadPanelAprobacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviando correos a los certificadores. Espere por favor....
        /// </summary>
        public static string labelLoadPanelCertificacion {
            get {
                return ResourceManager.GetString("labelLoadPanelCertificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso a la Aplicación.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos de Continuidad.
        /// </summary>
        public static string ProcedimientoBCPPageTitle {
            get {
                return ResourceManager.GetString("ProcedimientoBCPPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis de Impacto.
        /// </summary>
        public static string ProcedimientoBIAPageTitle {
            get {
                return ResourceManager.GetString("ProcedimientoBIAPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UEsDBBQAAgAIAG2TbkrYMAaQRAEAAJMCAAARAAAAZG9jUHJvcHMvY29yZS54bWydkktuwjAQhq9ieZ84CRVUUQgSRSyqIlUqUqvuLHsAq/FDtiFwpJ6hiy56oF6hiSERqKiLLmfm++f9/fFZTPayQjuwTmg1xmmcYASKaS7Ueoy3fhXd4klZMJMzbeHRagPWC3CokSmXczbGG+9NTojZ2irWdk04I1CBBOUdSeOU4J71YKW7KgiRM1IKfzBwFe2CPb13ogfruo7rQUCzJEnJy+LhiW1A0kgo56li0KmY6UUuEC5uZlNNcKWtpN6FJIayN7qGNtmQSPCUU09Ju4rI9LvAZcFZzixQr215r93XO5rRneBoDtaCsBpNq6a2LsgZV5z2cXQAR80c+XHqLvI8uJst57jMknQUJYMovVlmWZ6N8mz42ua60IcjVdT5RXO8lQA+Pfzdy2+8b0mefP/uqUsQmrKwE+17lWko2pvBunyr8gdQSwMEFAACAAgAbZNu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stringEmptyContenido {
            get {
                return ResourceManager.GetString("stringEmptyContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar a Excel.
        /// </summary>
        public static string stringExportExcel {
            get {
                return ResourceManager.GetString("stringExportExcel", resourceCulture);
            }
        }
    }
}
