//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BSMMovilResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BSMMovilResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.BSMMovilResource", typeof(BSMMovilResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivos Móviles.
        /// </summary>
        public static string HeaderPage {
            get {
                return ResourceManager.GetString("HeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conocer los tiempos críticos de recuperación, para volver al estado anterior del desastre y/o Interrupción..
        /// </summary>
        public static string Lista01Elemento01 {
            get {
                return ResourceManager.GetString("Lista01Elemento01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponer de un plan logístico de rápida actuación y respuesta, en caso de sufrir un incidente..
        /// </summary>
        public static string Lista01Elemento02 {
            get {
                return ResourceManager.GetString("Lista01Elemento02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducir gastos y pérdidas económicas considerables en caso de ocurrir un incidente que afecte el negocio..
        /// </summary>
        public static string Lista01Elemento03 {
            get {
                return ResourceManager.GetString("Lista01Elemento03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificar los recursos mínimos requeridos en la continuidad de los procesos del negocio..
        /// </summary>
        public static string Lista01Elemento04 {
            get {
                return ResourceManager.GetString("Lista01Elemento04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlar el impacto financiero y operacional, causado por la interrupción de la operación natural del negocio..
        /// </summary>
        public static string Lista01Elemento05 {
            get {
                return ResourceManager.GetString("Lista01Elemento05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimiento de Respuesta: incluyen la secuencia para escalar la ocurrencia de un evento que interrumpa las funciones operativas, desde el personal que detecta el evento, hasta el nivel necesario para la toma de decisiones, correspondientes a solucionar el problema así como los recursos necesarios para la comunicación del hecho..
        /// </summary>
        public static string Lista02Elemento01 {
            get {
                return ResourceManager.GetString("Lista02Elemento01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimiento de Recuperación: Descripción de las actividades o acciones para recuperar el proceso. Estos procedimientos se desarrollan con el nivel de detalle necesario para que un profesional del área, siguiendo las instrucciones del mismo, pueda levantar las operaciones necesarias para que los procesos del negocio estén operativos. Estos procedimientos se acompañan de:.
        /// </summary>
        public static string Lista02Elemento02 {
            get {
                return ResourceManager.GetString("Lista02Elemento02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentación o información vital para llevar a cabo la Recuperación..
        /// </summary>
        public static string Lista02Elemento02Subelemento01 {
            get {
                return ResourceManager.GetString("Lista02Elemento02Subelemento01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos necesarios para lograr la Recuperación..
        /// </summary>
        public static string Lista02Elemento02Subelemento02 {
            get {
                return ResourceManager.GetString("Lista02Elemento02Subelemento02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal y Proveedores claves..
        /// </summary>
        public static string Lista02Elemento02Subelemento03 {
            get {
                return ResourceManager.GetString("Lista02Elemento02Subelemento03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimiento de Reanudación: describe las actividades que se deben ejecutar para verificar y validar que las tareas del procedimiento de Recuperación fueron alcanzadas. Lista de comprobación o “Checklist”. Estos procedimientos se acompañan de:.
        /// </summary>
        public static string Lista02Elemento03 {
            get {
                return ResourceManager.GetString("Lista02Elemento03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentación o información vital para llevar a cabo la Reanudación..
        /// </summary>
        public static string Lista02Elemento03Subelemento01 {
            get {
                return ResourceManager.GetString("Lista02Elemento03Subelemento01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal y Proveedores claves..
        /// </summary>
        public static string Lista02Elemento03Subelemento02 {
            get {
                return ResourceManager.GetString("Lista02Elemento03Subelemento02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimiento de Restauración: Contiene una descripción de las condiciones actuales del ambiente de trabajo, en cuanto a Infraestructura física,  mobiliario, equipos, materiales, etc. Es documentado con la finalidad de estimar la realidad en la cual se desenvuelve la unidad operativa en la actualidad, esta información es muy útil cuando los equipos de continuidad, han de estimar las facilidades y la dotación necesaria al momento de recrear las  condiciones iniciales en la vuelta a la normalidad..
        /// </summary>
        public static string Lista02Elemento04 {
            get {
                return ResourceManager.GetString("Lista02Elemento04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una aplicación móvil es un sistema informático, diseñado para ser ejecutado en teléfonos inteligentes, tabletas y otros dispositivos móviles..
        /// </summary>
        public static string Parrafo01 {
            get {
                return ResourceManager.GetString("Parrafo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es un servicio alojado en Internet, mediante el cual el personal directivo y clave de una Empresa puede a través de dispositivos electrónicos por medio de Internet, consultar sus procedimientos de continuidad, para de ésta manera asegurar la Continuidad de las Operaciones Críticas de la Empresa..
        /// </summary>
        public static string Parrafo02 {
            get {
                return ResourceManager.GetString("Parrafo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder acceder a éste servicio, el personal de la Empresa debe poseer un dispositivo móvil habilitado técnicamente y ser autorizado para su uso a través de un “usuario” y un “password” debidamente permisado por la dirección de la empresa..
        /// </summary>
        public static string Parrafo03 {
            get {
                return ResourceManager.GetString("Parrafo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentro de los Beneficios de contar con Procedimientos de Continuidad documentados, se encuentran:.
        /// </summary>
        public static string Parrafo04 {
            get {
                return ResourceManager.GetString("Parrafo04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los Procedimientos de Continuidad desarrollados abarcan cuatro grandes fases, a saber:.
        /// </summary>
        public static string Parrafo05 {
            get {
                return ResourceManager.GetString("Parrafo05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es importante que estos procedimientos estén actualizados y disponibles en cualquier momento y desde cualquier parte, por el personal autorizado y los responsables de los mismos. Es por lo anterior que reviste singular importancia portar en ambiente Web “Cloud”, toda la información concerniente a la Continuidad de Negocios de la Organización..
        /// </summary>
        public static string Parrafo06 {
            get {
                return ResourceManager.GetString("Parrafo06", resourceCulture);
            }
        }
    }
}
