//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfidencialidadResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfidencialidadResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.ConfidencialidadResource", typeof(ConfidencialidadResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso de conexiones seguras con SSL para proteger la información que se transmite del navegador Web del cliente a.
        /// </summary>
        public static string Lista1Elemento1 {
            get {
                return ResourceManager.GetString("Lista1Elemento1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso de controles de seguridad para restringir el acceso a las bases de datos que albergan la información que permite identificar al usuario.
        /// </summary>
        public static string Lista1Elemento2 {
            get {
                return ResourceManager.GetString("Lista1Elemento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso restringido de los empleados a las bases de datos que contienen información personal y requisitos de confidencialidad impuestos a los empleados que las crean.
        /// </summary>
        public static string Lista1Elemento3 {
            get {
                return ResourceManager.GetString("Lista1Elemento3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligación contractual vinculante de los contratados externos de adoptar medidas técnicas y de organización que salvaguarden la información personal..
        /// </summary>
        public static string Lista1Elemento4 {
            get {
                return ResourceManager.GetString("Lista1Elemento4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregarle los productos y servicios de.
        /// </summary>
        public static string Lista2Elemento1Parte1 {
            get {
                return ResourceManager.GetString("Lista2Elemento1Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , así como comunicarse con el usuario por asuntos relativos a su cuenta o al servicio..
        /// </summary>
        public static string Lista2Elemento1Parte2 {
            get {
                return ResourceManager.GetString("Lista2Elemento1Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar los derechos de acceso o a otros servicios o programas de acceso restringido, además de permitir la compatibilidad con software de administración de derechos digitales.
        /// </summary>
        public static string Lista2Elemento2 {
            get {
                return ResourceManager.GetString("Lista2Elemento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determinar si cumple los requisitos mínimos del sistema para utilizar nuestros servicios y proporcionar información relativa a la compatibilidad con el usuario.
        /// </summary>
        public static string Lista2Elemento3 {
            get {
                return ResourceManager.GetString("Lista2Elemento3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitar al usuario a tomar parte en encuestas sobre los productos, los servicios, las noticias y los evento.
        /// </summary>
        public static string Lista2Elemento4 {
            get {
                return ResourceManager.GetString("Lista2Elemento4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofrecer actualizaciones de productos, contenidos y servicios.
        /// </summary>
        public static string Lista2Elemento5 {
            get {
                return ResourceManager.GetString("Lista2Elemento5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar de manera automática los productos de.
        /// </summary>
        public static string Lista2Elemento6Parte1 {
            get {
                return ResourceManager.GetString("Lista2Elemento6Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descargados.
        /// </summary>
        public static string Lista2Elemento6Parte2 {
            get {
                return ResourceManager.GetString("Lista2Elemento6Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determinar cómo se usan los servicios, incluidas las características del tráfico Web y el tipo de contenido más solicitado entre los usuarios de nuestros productos y servicios..
        /// </summary>
        public static string Lista2Elemento7 {
            get {
                return ResourceManager.GetString("Lista2Elemento7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Políticas de confidencialidad.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expresa su compromiso de proteger la privacidad de los usuarios. Lea la Declaración de privacidad online de.
        /// </summary>
        public static string Parrafo01Parte1 {
            get {
                return ResourceManager.GetString("Parrafo01Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que aparece a continuación. Esta Declaración de privacidad online de.
        /// </summary>
        public static string Parrafo01Parte2 {
            get {
                return ResourceManager.GetString("Parrafo01Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se aplica a los datos recopilados a través de la mayoría de sus servicios, así como a través de los servicios de consultoría y soporte técnico. No se aplica a sitios, servicios y productos de.
        /// </summary>
        public static string Parrafo01Parte3 {
            get {
                return ResourceManager.GetString("Parrafo01Parte3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que no muestren o que no incluyan un enlace a ella, o que cuenten con sus propias declaraciones de privacidad..
        /// </summary>
        public static string Parrafo01Parte4 {
            get {
                return ResourceManager.GetString("Parrafo01Parte4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En algunos sitios de.
        /// </summary>
        public static string Parrafo02Parte1 {
            get {
                return ResourceManager.GetString("Parrafo02Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , se le solicita que proporcione datos personales, como su dirección de correo electrónico, nombre, dirección del trabajo o de casa, o el número de teléfono. También se puede recopilar información demográfica; como su código postal, edad, género, preferencias, intereses y favoritos..
        /// </summary>
        public static string Parrafo02Parte2 {
            get {
                return ResourceManager.GetString("Parrafo02Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para obtener acceso a.
        /// </summary>
        public static string Parrafo03Parte1 {
            get {
                return ResourceManager.GetString("Parrafo03Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , se le solicitará que inicie sesión con una dirección de correo electrónico y una contraseña, a las que hacemos referencia como su ID o USUARIO. Como parte del proceso de creación de sus credenciales, puede que se le solicite también que indique preguntas y respuestas secretas, que usaremos para comprobar su identidad y ayudarle a restablecer su contraseña, así como una dirección de correo electrónico alternativa. Algunos servicios pueden requerir una mayor seguridad, en cuyo caso se le solicitará que cree [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Parrafo03Parte2 {
            get {
                return ResourceManager.GetString("Parrafo03Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podemos recopilar información acerca de su interacción con los sitios. Asimismo, podemos emplear tecnologías, como cookies y balizas web, para recopilar información acerca de las páginas que visita, los vínculos en los que hace clic y otras acciones que realiza en nuestros sitios y servicios. También recopilamos cierta información estándar que su explorador envía a los sitios web que visita, como su dirección IP, el tipo de explorador, las horas de acceso y direcciones de sitios web de referencia..
        /// </summary>
        public static string Parrafo04 {
            get {
                return ResourceManager.GetString("Parrafo04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para la fecha de emisión de esta política de confidencialidad,.
        /// </summary>
        public static string Parrafo05Parte1 {
            get {
                return ResourceManager.GetString("Parrafo05Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no recopila de forma consciente información personal que permita identificar a usuarios menores de edad..
        /// </summary>
        public static string Parrafo05Parte2 {
            get {
                return ResourceManager.GetString("Parrafo05Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos comprometemos a no vender, arrendar ni distribuir información de identificación personal a terceros sin su autorización, excepto lo estipulado más adelante..
        /// </summary>
        public static string Parrafo06 {
            get {
                return ResourceManager.GetString("Parrafo06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expresa su compromiso de proteger la seguridad de la información personal de los usuarios. Se usa una variedad de tecnologías y procedimientos de seguridad para proteger la información personal contra un acceso, uso o una divulgación no autorizados. Por ejemplo, almacenamos la información personal que nos proporciona en sistemas informáticos con acceso limitado, ubicados en instalaciones controladas. Si se usa una contraseña para ayudar a proteger sus cuentas e información personal, es su responsabilidad qu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Parrafo07 {
            get {
                return ResourceManager.GetString("Parrafo07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es consciente de que es un privilegio tenerle como cliente y se compromete a proteger sus datos personales. Utilizamos los siguientes controles para proteger sus datos personales:.
        /// </summary>
        public static string Parrafo08 {
            get {
                return ResourceManager.GetString("Parrafo08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos de carácter personal sirven a.
        /// </summary>
        public static string Parrafo09Parte1 {
            get {
                return ResourceManager.GetString("Parrafo09Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para lo siguiente:.
        /// </summary>
        public static string Parrafo09Parte2 {
            get {
                return ResourceManager.GetString("Parrafo09Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no emplea los datos personales del usuario para fines que no sean compatibles con los mencionados anteriormente..
        /// </summary>
        public static string Parrafo10Parte1 {
            get {
                return ResourceManager.GetString("Parrafo10Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se abstiene de vender, alquilar o revelar a asociados o servicios de contenido la información personal del usuario a no ser que éste exprese su conformidad..
        /// </summary>
        public static string Parrafo10Parte2 {
            get {
                return ResourceManager.GetString("Parrafo10Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En algunos casos, el acceso a determinados productos y servicios, como productos de suscripción de contenido o productos distribuidos por terceros, puede requerir la provisión de información personal a un tercero, como un proveedor o distribuidor de contenido. En tales situaciones, esto se determinará durante el proceso de registro, en las condiciones de uso, durante el proceso de distribución o de cualquier modo que se estime oportuno. El uso que haga de esta información el tercero, de un lado, y.
        /// </summary>
        public static string Parrafo11Parte1 {
            get {
                return ResourceManager.GetString("Parrafo11Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de otro, estará sujeto a sus respectivas políticas de confidencialidad. Para conocer el tratamiento que recibe por parte del asociado de contenido, es de rigor visitar su política de confidencialidad. Si el usuario está en desacuerdo con la transferencia de datos, no debe registrarse en el producto o servicio de que se trate. Asimismo, algunos proveedores o titulares de contenido pueden exigir a.
        /// </summary>
        public static string Parrafo11Parte2 {
            get {
                return ResourceManager.GetString("Parrafo11Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el suministro de información sobre el uso y el acceso como condición para otorgar sus derechos y licencias. En tales casos,.
        /// </summary>
        public static string Parrafo11Parte3 {
            get {
                return ResourceManager.GetString("Parrafo11Parte3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aporta al proveedor de contenido, entre otra información, datos sobre el uso del contenido, datos de acceso o información de índole demográfica, en ningún caso información que facilite la identificación personal (nombre o direcciones de correo electrónico)..
        /// </summary>
        public static string Parrafo11Parte4 {
            get {
                return ResourceManager.GetString("Parrafo11Parte4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Además,.
        /// </summary>
        public static string Parrafo12Parte1 {
            get {
                return ResourceManager.GetString("Parrafo12Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se reserva el derecho de revelar datos de carácter personal del usuario si así lo exige la ley o legislación vigente o si expone sus razones para creer que dicha actuación es necesaria para: (a) cumplir una orden judicial; (b) cumplir la orden de un órgano judicial competente de cualquier jurisdicción; (c) cumplir los trámites en procesos incoados contra.
        /// </summary>
        public static string Parrafo12Parte2 {
            get {
                return ResourceManager.GetString("Parrafo12Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; (d) proteger y defender los derechos o bienes de.
        /// </summary>
        public static string Parrafo12Parte3 {
            get {
                return ResourceManager.GetString("Parrafo12Parte3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; o bien (e) actuar de urgencia con el fin de proteger la seguridad personal de los usuarios de los productos de.
        /// </summary>
        public static string Parrafo12Parte4 {
            get {
                return ResourceManager.GetString("Parrafo12Parte4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o del público en general..
        /// </summary>
        public static string Parrafo12Parte5 {
            get {
                return ResourceManager.GetString("Parrafo12Parte5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los sitios Web de.
        /// </summary>
        public static string Parrafo13Parte1 {
            get {
                return ResourceManager.GetString("Parrafo13Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incluyen enlaces a otros sitios Web, productos y servicios. Debido a que.
        /// </summary>
        public static string Parrafo13Parte2 {
            get {
                return ResourceManager.GetString("Parrafo13Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no gestiona los sitios Web, productos y servicios de terceros, éstos no se rigen por esta política de confidencialidad..
        /// </summary>
        public static string Parrafo13Parte3 {
            get {
                return ResourceManager.GetString("Parrafo13Parte3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no se hace responsable de las prácticas de confidencialidad o el contenido de dichos productos o sitios. Consulte las respectivas políticas de confidencialidad para conocer la forma de recopilación de datos y su tratamiento..
        /// </summary>
        public static string Parrafo13Parte4 {
            get {
                return ResourceManager.GetString("Parrafo13Parte4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algunos de los datos de carácter personal recopilados por.
        /// </summary>
        public static string Parrafo14Parte1 {
            get {
                return ResourceManager.GetString("Parrafo14Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to son imprescindibles para ofrecerle el producto o servicio de.
        /// </summary>
        public static string Parrafo14Parte2 {
            get {
                return ResourceManager.GetString("Parrafo14Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elegido. El software de.
        /// </summary>
        public static string Parrafo14Parte3 {
            get {
                return ResourceManager.GetString("Parrafo14Parte3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puede incluir la posibilidad de desactivar algunas funciones de software con objeto de aumentar el grado de confidencialidad..
        /// </summary>
        public static string Parrafo14Parte4 {
            get {
                return ResourceManager.GetString("Parrafo14Parte4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En General, no enviamos mensajes de correo electrónico a los usuarios para presentar productos, novedades en los contenidos y ofertas especiales. Los productos, servicios y líneas de negocio independientes de.
        /// </summary>
        public static string Parrafo15Parte1 {
            get {
                return ResourceManager.GetString("Parrafo15Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podrán enviar mensajes de correo electrónico publicitarios y boletines por separado. Los únicos correos electrónicos que envíamos corresponden con datos necesarios para el funcionamiento o acceso a nuestros servicios o bien para informarle de cuestiones vitales del servicio técnico relativas a un producto o servicio de.
        /// </summary>
        public static string Parrafo15Parte2 {
            get {
                return ResourceManager.GetString("Parrafo15Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al igual que otros grandes sitios Web, aprovechamos las cookies para ofrecer al usuario una experiencia que se ajuste a sus intereses cuando visite nuestros sitios Web y use nuestros productos. Estos pequeños archivos nos sirven, asimismo, para analizar las características del tráfico que pasa por los sitios de.
        /// </summary>
        public static string Parrafo16Parte1 {
            get {
                return ResourceManager.GetString("Parrafo16Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y para autorizar el acceso a opciones de productos y contenido Premium o de prueba. Los datos personales que se hallen en estas cookies reciben el mismo trato de confidencialidad que el resto de la información que nos suministre el usuario..
        /// </summary>
        public static string Parrafo16Parte2 {
            get {
                return ResourceManager.GetString("Parrafo16Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisamos con frecuencia nuestra Política de confidencialidad para mantenerla actualizada con los productos, los servicios y las páginas Web de.
        /// </summary>
        public static string Parrafo17Parte1 {
            get {
                return ResourceManager.GetString("Parrafo17Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Se usa &quot;Actualizado&quot; para advertir a los usuarios sobre cambios recientes en el documento y para indicar la fecha de la última actualización. En ocasiones también incluimos las preguntas más frecuentes sobre productos concretos..
        /// </summary>
        public static string Parrafo17Parte2 {
            get {
                return ResourceManager.GetString("Parrafo17Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La política de confidencialidad no implica garantía alguna de.
        /// </summary>
        public static string Parrafo18Parte1 {
            get {
                return ResourceManager.GetString("Parrafo18Parte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se exime de toda responsabilidad por cualquier daño incidental, colateral o punitivo relacionado con la presente Política de confidencialidad. Esta Política de confidencialidad se rige por la legislación de Venezuela.
        /// </summary>
        public static string Parrafo18Parte2 {
            get {
                return ResourceManager.GetString("Parrafo18Parte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si tiene dudas sobre cualquier asunto relacionado con la confidencialidad de nuestros productos y servicios o si desea elevar una reclamación, póngase en contacto con nosotros..
        /// </summary>
        public static string Parrafo19 {
            get {
                return ResourceManager.GetString("Parrafo19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOPILACIÓN DE SU INFORMACIÓN PERSONAL.
        /// </summary>
        public static string Subtitulo01 {
            get {
                return ResourceManager.GetString("Subtitulo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGURIDAD DE SU INFORMACIÓN PERSONAL.
        /// </summary>
        public static string Subtitulo02 {
            get {
                return ResourceManager.GetString("Subtitulo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODO DE MANTENER LA INFORMACIÓN PERSONAL RECOPILADA DE FORMA SEGURA.
        /// </summary>
        public static string Subtitulo03 {
            get {
                return ResourceManager.GetString("Subtitulo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USO DE LA INFORMACIÓN PERSONAL RECOPILADA.
        /// </summary>
        public static string Subtitulo04 {
            get {
                return ResourceManager.GetString("Subtitulo04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SITUACIONES EN LAS QUE SE COMPARTE LA INFORMACIÓN DEL USUARIO CON TERCEROS Y MODO DE HACERLO.
        /// </summary>
        public static string Subtitulo05 {
            get {
                return ResourceManager.GetString("Subtitulo05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATURALEZA OBLIGATORIA U OPCIONAL DE LA INFORMACIÓN SOLICITADA.
        /// </summary>
        public static string Subtitulo06 {
            get {
                return ResourceManager.GetString("Subtitulo06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJES DE CORREO ELECTRÓNICO DE.
        /// </summary>
        public static string Subtitulo07 {
            get {
                return ResourceManager.GetString("Subtitulo07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGURIDAD DE LA INFORMACIÓN PERSONAL Y USO DE COOKIES.
        /// </summary>
        public static string Subtitulo08 {
            get {
                return ResourceManager.GetString("Subtitulo08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBIOS EN NUESTRA POLÍTICA DE CONFIDENCIALIDAD.
        /// </summary>
        public static string Subtitulo09 {
            get {
                return ResourceManager.GetString("Subtitulo09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSIBILIDAD DE ERROR EN EL FUNCIONAMIENTO.
        /// </summary>
        public static string Subtitulo10 {
            get {
                return ResourceManager.GetString("Subtitulo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULTAS SOBRE LA CONFIDENCIALIDAD.
        /// </summary>
        public static string Subtitulo11 {
            get {
                return ResourceManager.GetString("Subtitulo11", resourceCulture);
            }
        }
    }
}
