//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.ContactResource", typeof(ContactResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela.
        /// </summary>
        public static string Direccion1Header {
            get {
                return ResourceManager.GetString("Direccion1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Aplired C.A..
        /// </summary>
        public static string Direccion1Linea1 {
            get {
                return ResourceManager.GetString("Direccion1Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torre Morelos, Piso 4, oficina 4-B, Quebrada Honda, La Candelaria, 1010.
        /// </summary>
        public static string Direccion1Linea2 {
            get {
                return ResourceManager.GetString("Direccion1Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracas – Venezuela.
        /// </summary>
        public static string Direccion1Linea3 {
            get {
                return ResourceManager.GetString("Direccion1Linea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to España.
        /// </summary>
        public static string Direccion2Header {
            get {
                return ResourceManager.GetString("Direccion2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo APLIRED S.L..
        /// </summary>
        public static string Direccion2Linea1 {
            get {
                return ResourceManager.GetString("Direccion2Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guillén de Castro, 26 – 28017..
        /// </summary>
        public static string Direccion2Linea2 {
            get {
                return ResourceManager.GetString("Direccion2Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madrid – España.
        /// </summary>
        public static string Direccion2Linea3 {
            get {
                return ResourceManager.GetString("Direccion2Linea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        public static string Direccion3Header {
            get {
                return ResourceManager.GetString("Direccion3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Aplired S.A.S.
        /// </summary>
        public static string Direccion3Linea1 {
            get {
                return ResourceManager.GetString("Direccion3Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrera 11B- # 98 - 08, oficina 202.
        /// </summary>
        public static string Direccion3Linea2 {
            get {
                return ResourceManager.GetString("Direccion3Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bogotá – Colombia.
        /// </summary>
        public static string Direccion3Linea3 {
            get {
                return ResourceManager.GetString("Direccion3Linea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        public static string Direccion4Header {
            get {
                return ResourceManager.GetString("Direccion4Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Aplired S.A..
        /// </summary>
        public static string Direccion4Linea1 {
            get {
                return ResourceManager.GetString("Direccion4Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6ta Calle, 5 - 47, Zona 9, Edificio Vasil, 6to Nivel.
        /// </summary>
        public static string Direccion4Linea2 {
            get {
                return ResourceManager.GetString("Direccion4Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala – Guatemala.
        /// </summary>
        public static string Direccion4Linea3 {
            get {
                return ResourceManager.GetString("Direccion4Linea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacto.bcmweb@aplired.com.
        /// </summary>
        public static string EmailContacto {
            get {
                return ResourceManager.GetString("EmailContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha recibido un mensaje de contacto.
        /// </summary>
        public static string HeaderEmailApliredHtml {
            get {
                return ResourceManager.GetString("HeaderEmailApliredHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por Contactarnos.
        /// </summary>
        public static string HeaderEmailClienteHtml {
            get {
                return ResourceManager.GetString("HeaderEmailClienteHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        public static string labelAsunto {
            get {
                return ResourceManager.GetString("labelAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico:.
        /// </summary>
        public static string labelEmailContacto {
            get {
                return ResourceManager.GetString("labelEmailContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string labelMensaje {
            get {
                return ResourceManager.GetString("labelMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;img src=&quot;cid:Logo-BiaPlus&quot; width=&quot;80&quot; /&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;&lt;h1&gt;{0}&lt;/h1&gt;&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot; style=&quot;align-content:center; text-align:center;&quot;&gt;
        ///                &lt;h2&gt;{5}&lt;/h2&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot;&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MensajeEmailApliredHTML {
            get {
                return ResourceManager.GetString("MensajeEmailApliredHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha recibido un correo electrónico de contacto. {0} {0} La información recibida es la siguiente: {0} Nombre: {1} {0} Correo Electrónico: {2}{0} Asunto: {3} {0} Mensaje {4} .
        /// </summary>
        public static string MensajeEmailApliredTexto {
            get {
                return ResourceManager.GetString("MensajeEmailApliredTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;img src=&quot;cid:Logo-BiaPlus&quot; width=&quot;80&quot; /&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;&lt;h1&gt;{0}&lt;/h1&gt;&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot; style=&quot;align-content:center; text-align:center;&quot;&gt;
        ///                &lt;h2&gt;{2}&lt;/h2&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot;&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MensajeEmailClienteHTML {
            get {
                return ResourceManager.GetString("MensajeEmailClienteHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr/a {1}. {0} {0} Su mensaja ha sido enviado de manera satisfactoria. {0} Queremos agradecerle por contactarnos..
        /// </summary>
        public static string MensajeEmailClienteTexto {
            get {
                return ResourceManager.GetString("MensajeEmailClienteTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctenos.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedes.
        /// </summary>
        public static string SedesLabel {
            get {
                return ResourceManager.GetString("SedesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envíenos un Correo Electrónico a:.
        /// </summary>
        public static string SubHeaderCorreo {
            get {
                return ResourceManager.GetString("SubHeaderCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envíenos un Mensaje.
        /// </summary>
        public static string SubHeaderMensaje {
            get {
                return ResourceManager.GetString("SubHeaderMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto desde BCMWeb.
        /// </summary>
        public static string SubjectEmailAplired {
            get {
                return ResourceManager.GetString("SubjectEmailAplired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta de contacto en BCMWeb.
        /// </summary>
        public static string SubjectEmailCliente {
            get {
                return ResourceManager.GetString("SubjectEmailCliente", resourceCulture);
            }
        }
    }
}
