//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DispositivoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DispositivoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.DispositivoResource", typeof(DispositivoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación de Dispositvos Móviles Registrados.
        /// </summary>
        public static string GridTitle {
            get {
                return ResourceManager.GetString("GridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación de Conexiones.
        /// </summary>
        public static string gvConexionesTitle {
            get {
                return ResourceManager.GetString("gvConexionesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escenario.
        /// </summary>
        public static string labelComboEvento {
            get {
                return ResourceManager.GetString("labelComboEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección IP.
        /// </summary>
        public static string labelDireccionIP {
            get {
                return ResourceManager.GetString("labelDireccionIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string labelEmpresa {
            get {
                return ResourceManager.GetString("labelEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabricante.
        /// </summary>
        public static string labelFabricante {
            get {
                return ResourceManager.GetString("labelFabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de conexión.
        /// </summary>
        public static string labelFechaConexion {
            get {
                return ResourceManager.GetString("labelFechaConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de descarga.
        /// </summary>
        public static string labelFechaDescarga {
            get {
                return ResourceManager.GetString("labelFechaDescarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de envío.
        /// </summary>
        public static string labelFechaEnvio {
            get {
                return ResourceManager.GetString("labelFechaEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Registro.
        /// </summary>
        public static string labelFechaRegistro {
            get {
                return ResourceManager.GetString("labelFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Última Conexión.
        /// </summary>
        public static string labelFechaUltimaConexion {
            get {
                return ResourceManager.GetString("labelFechaUltimaConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI.
        /// </summary>
        public static string labelIdUnicoDispositivo {
            get {
                return ResourceManager.GetString("labelIdUnicoDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar todas las selecciones.
        /// </summary>
        public static string labelLnkClearSelection {
            get {
                return ResourceManager.GetString("labelLnkClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar todos los dispositivos..
        /// </summary>
        public static string labelLnkSelectAllRows {
            get {
                return ResourceManager.GetString("labelLnkSelectAllRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string labelModelo {
            get {
                return ResourceManager.GetString("labelModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataforma.
        /// </summary>
        public static string labelPlataforma {
            get {
                return ResourceManager.GetString("labelPlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string labelTipo {
            get {
                return ResourceManager.GetString("labelTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string labelUsuario {
            get {
                return ResourceManager.GetString("labelUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión.
        /// </summary>
        public static string labelVersion {
            get {
                return ResourceManager.GetString("labelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitar filtro.
        /// </summary>
        public static string lblClearFilter {
            get {
                return ResourceManager.GetString("lblClearFilter", resourceCulture);
            }
        }
    }
}
