//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.EditorResources", typeof(EditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede ser editado.
        /// </summary>
        public static string EditableText {
            get {
                return ResourceManager.GetString("EditableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede ser editado.
        /// </summary>
        public static string NoEditableText {
            get {
                return ResourceManager.GetString("NoEditableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string OpenCustomText {
            get {
                return ResourceManager.GetString("OpenCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseño.
        /// </summary>
        public static string RibbonDesignTab {
            get {
                return ResourceManager.GetString("RibbonDesignTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentación.
        /// </summary>
        public static string RibbonLayoutTab {
            get {
                return ResourceManager.GetString("RibbonLayoutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string SaveCustomText {
            get {
                return ResourceManager.GetString("SaveCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Archivo.
        /// </summary>
        public static string UploadControlText {
            get {
                return ResourceManager.GetString("UploadControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir archivos.
        /// </summary>
        public static string UploadFormHeader {
            get {
                return ResourceManager.GetString("UploadFormHeader", resourceCulture);
            }
        }
    }
}
