//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, resuelva todos los errores..
        /// </summary>
        public static string AllErrors {
            get {
                return ResourceManager.GetString("AllErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido bloqueado. Por favor comuníquese con el administrador..
        /// </summary>
        public static string BloqueadoErrorMessage {
            get {
                return ResourceManager.GetString("BloqueadoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es inocrrecta o la nueva contraseña es inválida.
        /// </summary>
        public static string ChangePasswordFailError {
            get {
                return ResourceManager.GetString("ChangePasswordFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {1} y la {0} no coinciden..
        /// </summary>
        public static string CompareErrorFemalevsFemale {
            get {
                return ResourceManager.GetString("CompareErrorFemalevsFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {1} y el {0} no coinciden..
        /// </summary>
        public static string CompareErrorFemalevsMale {
            get {
                return ResourceManager.GetString("CompareErrorFemalevsMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {1} y la {0} no coinciden..
        /// </summary>
        public static string CompareErrorMalevsFemale {
            get {
                return ResourceManager.GetString("CompareErrorMalevsFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {1} y el {0} no coinciden..
        /// </summary>
        public static string CompareErrorMalevsMale {
            get {
                return ResourceManager.GetString("CompareErrorMalevsMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se encuentra conectado. Por favor comuníquese con el administrador..
        /// </summary>
        public static string ConectadoErrorMessage {
            get {
                return ResourceManager.GetString("ConectadoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un error desconocido ocurrió. Verifique su entrada e inténtelo de nuevo. Si el problema persiste, póngase en contacto con el administrador del sistema.
        /// </summary>
        public static string defaultError {
            get {
                return ResourceManager.GetString("defaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario registrado con el correo electrónico indicado. Por favor registre una dirección de correo electrónico diferente.
        /// </summary>
        public static string DuplicateEmailError {
            get {
                return ResourceManager.GetString("DuplicateEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de usuario ya existe. Por favor registro un código de usuario diferente.
        /// </summary>
        public static string DuplicateUserNameError {
            get {
                return ResourceManager.GetString("DuplicateUserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido Eliminado. Por favor comuníquese con el administrador..
        /// </summary>
        public static string EliminadoErrorMessage {
            get {
                return ResourceManager.GetString("EliminadoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor registre una dirección de correo electrónico válida.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor registre al menos un aprobador.
        /// </summary>
        public static string ErrorAprobaciones {
            get {
                return ResourceManager.GetString("ErrorAprobaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor registre al menos un certificador.
        /// </summary>
        public static string ErrorCertificaciones {
            get {
                return ResourceManager.GetString("ErrorCertificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registrar al menos una entrevista.
        /// </summary>
        public static string ErrorEntrevistas {
            get {
                return ResourceManager.GetString("ErrorEntrevistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registar al menos una persona clave.
        /// </summary>
        public static string ErrorPersonasClaves {
            get {
                return ResourceManager.GetString("ErrorPersonasClaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registar al menos un proceso.
        /// </summary>
        public static string ErrorProcesos {
            get {
                return ResourceManager.GetString("ErrorProcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} no puede ser mayor a {1}.
        /// </summary>
        public static string FechaMayorIgualQueFecha {
            get {
                return ResourceManager.GetString("FechaMayorIgualQueFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} no puede ser mayor a la fecha de hoy.
        /// </summary>
        public static string FechaMayorIgualQueHoy {
            get {
                return ResourceManager.GetString("FechaMayorIgualQueHoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} no puede ser menor a {1).
        /// </summary>
        public static string FechaMenorIgualQueFecha {
            get {
                return ResourceManager.GetString("FechaMenorIgualQueFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} no puede ser menor a la fecha de hoy.
        /// </summary>
        public static string FechaMenorIgualQueHoy {
            get {
                return ResourceManager.GetString("FechaMenorIgualQueHoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again.
        /// </summary>
        public static string InvalidAnswerError {
            get {
                return ResourceManager.GetString("InvalidAnswerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico es inválido. Por favor verifique e intente nuevamente.
        /// </summary>
        public static string InvalidEmailError {
            get {
                return ResourceManager.GetString("InvalidEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} registrada no es válida..
        /// </summary>
        public static string InvalidoErrorFemale {
            get {
                return ResourceManager.GetString("InvalidoErrorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} registrado no es válido..
        /// </summary>
        public static string InvalidoErrorMale {
            get {
                return ResourceManager.GetString("InvalidoErrorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña indicada no es válida. Por favor indique una nueva contraseña.
        /// </summary>
        public static string InvalidPasswordError {
            get {
                return ResourceManager.GetString("InvalidPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La pregunta de recuperación de contraseña proporcionada no es válida. Compruebe el valor y vuelva a intentarlo.
        /// </summary>
        public static string InvalidQuestionError {
            get {
                return ResourceManager.GetString("InvalidQuestionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario proporcionado no es válido. Compruebe el valor y vuelva a intentarlo.
        /// </summary>
        public static string InvalidUserNameError {
            get {
                return ResourceManager.GetString("InvalidUserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de usuario o la contraseña no son válidos.
        /// </summary>
        public static string LoginFailError {
            get {
                return ResourceManager.GetString("LoginFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proveedor de autenticación devolvió un error. Verifique su entrada e inténtelo de nuevo. Si el problema persiste, póngase en contacto con el administrador del sistema.
        /// </summary>
        public static string ProviderError {
            get {
                return ResourceManager.GetString("ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} debe estar entre {1} y {2}.
        /// </summary>
        public static string RangeErrorFemale {
            get {
                return ResourceManager.GetString("RangeErrorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} debe estar entre {1} y {2}.
        /// </summary>
        public static string RangeErrorMale {
            get {
                return ResourceManager.GetString("RangeErrorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las {0} deben estar entre {1} y {2}.
        /// </summary>
        public static string RangeErrorMultipleFemale {
            get {
                return ResourceManager.GetString("RangeErrorMultipleFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los {0} deben estar entre {1} y {2}.
        /// </summary>
        public static string RangeErrorMultipleMale {
            get {
                return ResourceManager.GetString("RangeErrorMultipleMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} no es válida..
        /// </summary>
        public static string RegexErrorFemale {
            get {
                return ResourceManager.GetString("RegexErrorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} no es válido..
        /// </summary>
        public static string RegexErrorMale {
            get {
                return ResourceManager.GetString("RegexErrorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registrar al menos una dirección.
        /// </summary>
        public static string RemoteDireccion {
            get {
                return ResourceManager.GetString("RemoteDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registrar al menos un correo electrónico.
        /// </summary>
        public static string RemoteEmail {
            get {
                return ResourceManager.GetString("RemoteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registrar al menos un número telefónico.
        /// </summary>
        public static string RemoteTelefono {
            get {
                return ResourceManager.GetString("RemoteTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} debe ser registrada.
        /// </summary>
        public static string RequiredErrorFemale {
            get {
                return ResourceManager.GetString("RequiredErrorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} debe ser registrado.
        /// </summary>
        public static string RequiredErrorMale {
            get {
                return ResourceManager.GetString("RequiredErrorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} debe tener al menos {2} caracteres de longitud..
        /// </summary>
        public static string StringLengthErrorFemale {
            get {
                return ResourceManager.GetString("StringLengthErrorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} debe tener al menos {2} caracteres de longitud..
        /// </summary>
        public static string StringLengthErrorMale {
            get {
                return ResourceManager.GetString("StringLengthErrorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cancelado la solicitud de creación de usuarios. Verifique su entrada e inténtelo de nuevo. Si el problema persiste, póngase en contacto con el administrador del sistema.
        /// </summary>
        public static string UserRejectedError {
            get {
                return ResourceManager.GetString("UserRejectedError", resourceCulture);
            }
        }
    }
}
