//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FAQResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FAQResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.FAQResource", typeof(FAQResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para mantener la continuidad de los servicios de la empresa y de los procesos críticos, así como la disminución de impactos ante eventos inesperados o desastres..
        /// </summary>
        public static string Lista1Elemento1 {
            get {
                return ResourceManager.GetString("Lista1Elemento1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder identificar los diversos eventos que pueden impactar sobre la continuidad de las operaciones y su impacto en el negocio..
        /// </summary>
        public static string Lista1Elemento2 {
            get {
                return ResourceManager.GetString("Lista1Elemento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para conocer los tiempos críticos de recuperación, para volver al estado anterior de la compañía..
        /// </summary>
        public static string Lista1Elemento3 {
            get {
                return ResourceManager.GetString("Lista1Elemento3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder identificar aquellos puntos más débiles de la infraestructura, que son susceptibles de sufrir un incidente y afectar la continuidad del negocio..
        /// </summary>
        public static string Lista1Elemento4 {
            get {
                return ResourceManager.GetString("Lista1Elemento4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para disponer de un plan logístico de rápida actuación y respuesta, en caso de sufrir un incidente..
        /// </summary>
        public static string Lista1Elemento5 {
            get {
                return ResourceManager.GetString("Lista1Elemento5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para determinar con anterioridad  cuales son las tareas y funciones que deberán reponerse en primer lugar..
        /// </summary>
        public static string Lista1Elemento6 {
            get {
                return ResourceManager.GetString("Lista1Elemento6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toda organización depende de sus recursos, del personal y de las tareas que día a día son ejecutadas con el fin de mantener los beneficios y la estabilidad. La mayoría posee bienes tangibles, empleados, sistemas y tecnologías de información, etc. Si alguno de estos componentes es dañado o deja de estar accesible por la razón que sea, la organización puede paralizarse. Cuanto mayor sea el tiempo de inactividad, mayor es la probabilidad de que tenga que comenzar de nuevo desde cero. Incluso muchas organizacio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Lista1Elemento7 {
            get {
                return ResourceManager.GetString("Lista1Elemento7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información General.
        /// </summary>
        public static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como paso previo al proceso formal de desarrollar e implantar un plan de continuidad de negocio, toda organización debe tener en consideración varios aspectos claves, tales como:.
        /// </summary>
        public static string Parrafo1 {
            get {
                return ResourceManager.GetString("Parrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toda estrategia para abordar la implantación de un Plan de  Continuidad de Negocio requiere de tiempo y recursos (humanos, económicos e incluso tecnológicos). Dicho requerimiento convierte a las direcciones de las organizaciones en un componente clave para apoyar la gestión de continuidad y dotar de  tales recursos a la organización..
        /// </summary>
        public static string Parrafo2 {
            get {
                return ResourceManager.GetString("Parrafo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo y recursos:.
        /// </summary>
        public static string Parrafo2Span1 {
            get {
                return ResourceManager.GetString("Parrafo2Span1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La alta dirección de la Organización, como  ente que toma las decisiones y proporciona los fondos necesarios, debe ser concienciada y debe estar convencida de la necesidad  de este tipo de planes. Esta misión de concienciación a menudo resulta un proceso complejo por varias razones: los canales de  comunicación con la dirección no siempre son fluidos, el lenguaje empleado en términos de “riesgo”, “impacto”,  “vulnerabilidad” y otros conceptos relacionados con la seguridad y las tecnologías de la información [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Parrafo3 {
            get {
                return ResourceManager.GetString("Parrafo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implicación y compromiso de la dirección:.
        /// </summary>
        public static string Parrafo3Span1 {
            get {
                return ResourceManager.GetString("Parrafo3Span1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un paso clave que una organización debe abordar cuando decide impulsar un plan de continuidad de negocio es decidir acerca del alcance del mismo, es importante determinar qué áreas,  procesos de negocio o productos/servicios de la organización serán incluidos en el plan. Incluso en los casos en los que la  organización tenga varias sedes, será necesario establecer un alcance geográfico..
        /// </summary>
        public static string Parrafo4 {
            get {
                return ResourceManager.GetString("Parrafo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir el alcance:.
        /// </summary>
        public static string Parrafo4Span1 {
            get {
                return ResourceManager.GetString("Parrafo4Span1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un plan de continuidad de negocio  impacta y necesita del apoyo y la colaboración de las diferentes áreas de la organización: los proyectos de continuidad de  negocio tienen que contar con enfoques no solo tecnológicos, sino también de negocio (relación con proveedores de servicio,  recursos humanos, atención al cliente, recursos financieros, recurso logísticos, etc.)..
        /// </summary>
        public static string Parrafo5 {
            get {
                return ResourceManager.GetString("Parrafo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaboración de las áreas que componen la empresa:.
        /// </summary>
        public static string Parrafo5Span1 {
            get {
                return ResourceManager.GetString("Parrafo5Span1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conocer si es necesario disponer o no  de ayuda especializada y saber dónde encontrarla, ya que muchos de los problemas a los que se tiene que enfrentar una  organización para implantar su plan de continuidad de negocio ya han sido analizados y solucionados por otras empresas  previamente..
        /// </summary>
        public static string Parrafo6 {
            get {
                return ResourceManager.GetString("Parrafo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantearse la necesidad de asesoramiento externo:.
        /// </summary>
        public static string Parrafo6Span1 {
            get {
                return ResourceManager.GetString("Parrafo6Span1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Plan debe mantenerse actualizado para que sea útil y efectivo en casos de crisis y desastres, por lo que es necesario que tanto los responsables de los procesos críticos como el personal de Continuidad de la Organización se encarguen de llevar a cabo todas las actualizaciones necesarias (de personal, infraestructura, procesos, tecnología, etc.)..
        /// </summary>
        public static string Parrafo7 {
            get {
                return ResourceManager.GetString("Parrafo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. ¿Por qué es necesario contar con un Plan de Continuidad del Negocio?.
        /// </summary>
        public static string Pregunta1 {
            get {
                return ResourceManager.GetString("Pregunta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.	¿Por dónde empezar para llevar a cabo un Plan de Continuidad del Negocio?.
        /// </summary>
        public static string Pregunta2 {
            get {
                return ResourceManager.GetString("Pregunta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.	¿Quién debe realizar los mantenimientos y/o actualizaciones?.
        /// </summary>
        public static string Pregunta3 {
            get {
                return ResourceManager.GetString("Pregunta3", resourceCulture);
            }
        }
    }
}
