//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FichaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FichaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.FichaResource", typeof(FichaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string captionCargo {
            get {
                return ResourceManager.GetString("captionCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string captionCiudad {
            get {
                return ResourceManager.GetString("captionCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string captionEmail {
            get {
                return ResourceManager.GetString("captionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string captionEstado {
            get {
                return ResourceManager.GetString("captionEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string captionEstatusUsuario {
            get {
                return ResourceManager.GetString("captionEstatusUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Estatus Usuario.
        /// </summary>
        public static string captionFechaEU {
            get {
                return ResourceManager.GetString("captionFechaEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Última Conexión.
        /// </summary>
        public static string captionFechaUC {
            get {
                return ResourceManager.GetString("captionFechaUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Entrevistado.
        /// </summary>
        public static string captionGrupo1 {
            get {
                return ResourceManager.GetString("captionGrupo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de la Entrevista.
        /// </summary>
        public static string captionGrupo2 {
            get {
                return ResourceManager.GetString("captionGrupo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobadores.
        /// </summary>
        public static string captionGrupo3 {
            get {
                return ResourceManager.GetString("captionGrupo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificadores.
        /// </summary>
        public static string captionGrupo4 {
            get {
                return ResourceManager.GetString("captionGrupo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas Claves.
        /// </summary>
        public static string captionGrupo5 {
            get {
                return ResourceManager.GetString("captionGrupo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesos.
        /// </summary>
        public static string captionGrupo6 {
            get {
                return ResourceManager.GetString("captionGrupo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro. de Cédula:.
        /// </summary>
        public static string captionIdentificacion {
            get {
                return ResourceManager.GetString("captionIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string captionIdPersonaDireccion {
            get {
                return ResourceManager.GetString("captionIdPersonaDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string captionIdTelefono {
            get {
                return ResourceManager.GetString("captionIdTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string captionNivelUsuario {
            get {
                return ResourceManager.GetString("captionNivelUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string captionNombre {
            get {
                return ResourceManager.GetString("captionNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Teléfono.
        /// </summary>
        public static string captionNroTelefono {
            get {
                return ResourceManager.GetString("captionNroTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string captionPais {
            get {
                return ResourceManager.GetString("captionPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiere Certificación.
        /// </summary>
        public static string captionRequiereCertificacion {
            get {
                return ResourceManager.GetString("captionRequiereCertificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Dirección.
        /// </summary>
        public static string captionTipoDireccion {
            get {
                return ResourceManager.GetString("captionTipoDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Correo Electrónico.
        /// </summary>
        public static string captionTipoEmail {
            get {
                return ResourceManager.GetString("captionTipoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Teléfono.
        /// </summary>
        public static string captionTipoTelefono {
            get {
                return ResourceManager.GetString("captionTipoTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        public static string captionUbicacion {
            get {
                return ResourceManager.GetString("captionUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Padre.
        /// </summary>
        public static string captionUnidadPadre {
            get {
                return ResourceManager.GetString("captionUnidadPadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Organizativa.
        /// </summary>
        public static string captionUO {
            get {
                return ResourceManager.GetString("captionUO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Persona.
        /// </summary>
        public static string headerPopup {
            get {
                return ResourceManager.GetString("headerPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Cargos.
        /// </summary>
        public static string headerPopupCargo {
            get {
                return ResourceManager.GetString("headerPopupCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Unidades Organizativas.
        /// </summary>
        public static string headerPopupUnidadOrganizativa {
            get {
                return ResourceManager.GetString("headerPopupUnidadOrganizativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-999,000,000.
        /// </summary>
        public static string MaskIdentificacion {
            get {
                return ResourceManager.GetString("MaskIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correos Electrónicos.
        /// </summary>
        public static string personaGrupoCorreos {
            get {
                return ResourceManager.GetString("personaGrupoCorreos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Básicos.
        /// </summary>
        public static string personaGrupoDatos {
            get {
                return ResourceManager.GetString("personaGrupoDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcciones.
        /// </summary>
        public static string personaGrupoDireccion {
            get {
                return ResourceManager.GetString("personaGrupoDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonos.
        /// </summary>
        public static string personaGrupoTelefono {
            get {
                return ResourceManager.GetString("personaGrupoTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VEJGPvejgp]-[0-9](9).
        /// </summary>
        public static string RegexIdentiticacion {
            get {
                return ResourceManager.GetString("RegexIdentiticacion", resourceCulture);
            }
        }
    }
}
