//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ForgotPasswordResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForgotPasswordResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.ForgotPasswordResource", typeof(ForgotPasswordResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string ButtonSubmitString {
            get {
                return ResourceManager.GetString("ButtonSubmitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;img src=&quot;cid:Logo-BiaPlus&quot; width=&quot;80&quot; /&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;&lt;h1&gt;{0}&lt;/h1&gt;&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot; style=&quot;align-content:center; text-align:center;&quot;&gt;
        ///                &lt;h2&gt;{3}&lt;/h2&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot;&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContenidoEmailHTML {
            get {
                return ResourceManager.GetString("ContenidoEmailHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado/a {2}. {0} {0} Este correo le ha sido enviado como respuesta a su requerimiento por olvidar su contraseña. {0} Haga click en el siguiente enlace para ir al sitio web de BCMweb y modificar su contraseña. {0} {1} {0} Si Ud. no ha realizado la solicitud ignore este correo..
        /// </summary>
        public static string ContenidoEmailTexto {
            get {
                return ResourceManager.GetString("ContenidoEmailTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string EmailLabelString {
            get {
                return ResourceManager.GetString("EmailLabelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico de confirmación enviado.
        /// </summary>
        public static string EmailSentHeaderString {
            get {
                return ResourceManager.GetString("EmailSentHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado un correo a su cuenta de correo electrónico. Por favor verifique su correo electrónico y siga las indicaciones. En el caso de que no reciba el correo electrónico en un corto tiempo, verifique la carpeta de spam y/o vuelva a solicitar el envío del mismo procesando de nuevo la opción de olvidó contraseña..
        /// </summary>
        public static string EmailSentText {
            get {
                return ResourceManager.GetString("EmailSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidó su contraseña?.
        /// </summary>
        public static string HeaderString {
            get {
                return ResourceManager.GetString("HeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña reestablecida.
        /// </summary>
        public static string PasswordChangeHeader {
            get {
                return ResourceManager.GetString("PasswordChangeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haga click aquí para iniciar sessión.
        /// </summary>
        public static string PasswordChangeLink {
            get {
                return ResourceManager.GetString("PasswordChangeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña a sido reestablecida satisfactoriamente, Por favor.
        /// </summary>
        public static string PasswordChangeText {
            get {
                return ResourceManager.GetString("PasswordChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        public static string PasswordConfirmLabelString {
            get {
                return ResourceManager.GetString("PasswordConfirmLabelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña ha sido modificada satisfactoriamente..
        /// </summary>
        public static string PasswordConfirmSubTitle {
            get {
                return ResourceManager.GetString("PasswordConfirmSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string PasswordLabelString {
            get {
                return ResourceManager.GetString("PasswordLabelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga click aquí para iniciar sesión..
        /// </summary>
        public static string PaswordConfirmLink {
            get {
                return ResourceManager.GetString("PaswordConfirmLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de contraseña confirmado.
        /// </summary>
        public static string PaswordConfirmTitle {
            get {
                return ResourceManager.GetString("PaswordConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar contraseña.
        /// </summary>
        public static string RecuperarHeaderString {
            get {
                return ResourceManager.GetString("RecuperarHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reestablecer contraseña.
        /// </summary>
        public static string ResetPasswordString {
            get {
                return ResourceManager.GetString("ResetPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reestabler su contraseña.
        /// </summary>
        public static string ResetPasswordSubHeaderString {
            get {
                return ResourceManager.GetString("ResetPasswordSubHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su dirección de correo electrónico.
        /// </summary>
        public static string SubHeaderString {
            get {
                return ResourceManager.GetString("SubHeaderString", resourceCulture);
            }
        }
    }
}
