//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.LoginResource", typeof(LoginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso al sistema.
        /// </summary>
        public static string accountHeader {
            get {
                return ResourceManager.GetString("accountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string botLoginText {
            get {
                return ResourceManager.GetString("botLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string captionEmail {
            get {
                return ResourceManager.GetString("captionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        public static string captionNewPassword {
            get {
                return ResourceManager.GetString("captionNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        public static string captionOldPassword {
            get {
                return ResourceManager.GetString("captionOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string captionPassword {
            get {
                return ResourceManager.GetString("captionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme su contraseña.
        /// </summary>
        public static string captionPasswordConfirm {
            get {
                return ResourceManager.GetString("captionPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string captionUsername {
            get {
                return ResourceManager.GetString("captionUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPRESA:.
        /// </summary>
        public static string EmpresaLabelString {
            get {
                return ResourceManager.GetString("EmpresaLabelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización de contraseña.
        /// </summary>
        public static string HeaderPrimeraVez {
            get {
                return ResourceManager.GetString("HeaderPrimeraVez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indique su correo electrónico.
        /// </summary>
        public static string helpTextEmail {
            get {
                return ResourceManager.GetString("helpTextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indique su contraseña.
        /// </summary>
        public static string helpTextPassword {
            get {
                return ResourceManager.GetString("helpTextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ud. está ingresando por primera vez a la aplicacion, por esta razón le solicitamos que actualice su contraseña con una contraseña que le sea familiar y pueda recordar fácilmente.
        /// </summary>
        public static string loginPrimeraVezLinea1 {
            get {
                return ResourceManager.GetString("loginPrimeraVezLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, registre su código de usuario y su contraseña.
        /// </summary>
        public static string loginTextoLinea1 {
            get {
                return ResourceManager.GetString("loginTextoLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string LogOutString {
            get {
                return ResourceManager.GetString("LogOutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido:.
        /// </summary>
        public static string WelcomeString {
            get {
                return ResourceManager.GetString("WelcomeString", resourceCulture);
            }
        }
    }
}
