//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PDFResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PDFResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.PDFResource", typeof(PDFResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos de Continuidad.
        /// </summary>
        public static string BCPTituloString {
            get {
                return ResourceManager.GetString("BCPTituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis de Impacto.
        /// </summary>
        public static string BIATituloString {
            get {
                return ResourceManager.GetString("BIATituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar PDF.
        /// </summary>
        public static string BotonGenerarPDFString {
            get {
                return ResourceManager.GetString("BotonGenerarPDFString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capítulo.
        /// </summary>
        public static string CeldaCapituloHeader {
            get {
                return ResourceManager.GetString("CeldaCapituloHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string CeldaPaginaHeader {
            get {
                return ResourceManager.GetString("CeldaPaginaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido.
        /// </summary>
        public static string ContenidoTituloString {
            get {
                return ResourceManager.GetString("ContenidoTituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estructura de Continuidad.
        /// </summary>
        public static string ETCTituloString {
            get {
                return ResourceManager.GetString("ETCTituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estrategias de Continuidad.
        /// </summary>
        public static string ETGTituloString {
            get {
                return ResourceManager.GetString("ETGTituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha: {0}.
        /// </summary>
        public static string FechaHeaderString {
            get {
                return ResourceManager.GetString("FechaHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Aplired, C.A., Torre Morelos, Piso 4, ofc.4-B, Quebrada Honda, La Candelaria, Caracas – Venezuela.
        /// </summary>
        public static string FooterStringLinea1 {
            get {
                return ResourceManager.GetString("FooterStringLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefax: (58 212) 578.4565,  website: www.aplired.com,  e-mail: aplired@aplired.com.
        /// </summary>
        public static string FooterStringLinea2 {
            get {
                return ResourceManager.GetString("FooterStringLinea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidentes Experimentados.
        /// </summary>
        public static string INCTituloString {
            get {
                return ResourceManager.GetString("INCTituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Adiestramiento.
        /// </summary>
        public static string PADTituloString {
            get {
                return ResourceManager.GetString("PADTituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pág. {0}.
        /// </summary>
        public static string PaginaHeaderString {
            get {
                return ResourceManager.GetString("PaginaHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Políticas de Continuidad.
        /// </summary>
        public static string PLCTituloString {
            get {
                return ResourceManager.GetString("PLCTituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Manejo de Incidentes.
        /// </summary>
        public static string PMITituloString {
            get {
                return ResourceManager.GetString("PMITituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Mantenimiento.
        /// </summary>
        public static string PMTTituloString {
            get {
                return ResourceManager.GetString("PMTTituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan para Pruebas y Ejercicios.
        /// </summary>
        public static string PPETituloString {
            get {
                return ResourceManager.GetString("PPETituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Trabajo.
        /// </summary>
        public static string PTITituloString {
            get {
                return ResourceManager.GetString("PTITituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis de Riesgo.
        /// </summary>
        public static string RSGTituloString {
            get {
                return ResourceManager.GetString("RSGTituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Continuidad del Negocio.
        /// </summary>
        public static string TítuloDocumento {
            get {
                return ResourceManager.GetString("TítuloDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación de Usuarios.
        /// </summary>
        public static string USRTituloString {
            get {
                return ResourceManager.GetString("USRTituloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ésta opción permite generar el documento en formato PDF ..
        /// </summary>
        public static string ViewParrafo1 {
            get {
                return ResourceManager.GetString("ViewParrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento resultante en PDF, podrá ser consultado por las personas autorizadas, desde la aplicación. En el caso de que el documento se encuentre certificado, podrá ser visto desde los dispositivos móviles, por aquellos usuarios con acceso permitido para el módulo..
        /// </summary>
        public static string ViewParrafo2 {
            get {
                return ResourceManager.GetString("ViewParrafo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento puede ser generado las veces que lo considere necesario. No se guardarán versiones de los documentos en formato PDF y siempre estará disponible el último documento generado. Para generar el documento, deberá presionar el botón que se encuentra en la parte inferior derecha de la pantalla identidicado como {0}..
        /// </summary>
        public static string ViewParrafo3 {
            get {
                return ResourceManager.GetString("ViewParrafo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una vez finalizada la generación del documento, se abrirá una nueva ventana que le permitirá ver el documento resultante..
        /// </summary>
        public static string ViewParrafo4 {
            get {
                return ResourceManager.GetString("ViewParrafo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En caso de que la ventana nueva no aparezca, verifique que su explorador permite la apertura de ventanas emergentes desde este sitio web..
        /// </summary>
        public static string ViewParrafo5 {
            get {
                return ResourceManager.GetString("ViewParrafo5", resourceCulture);
            }
        }
    }
}
