//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PerfilResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PerfilResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.PerfilResource", typeof(PerfilResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización del Perfil de Usuario.
        /// </summary>
        public static string AsuntoEmailString {
            get {
                return ResourceManager.GetString("AsuntoEmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string captionEmail {
            get {
                return ResourceManager.GetString("captionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string captionNombre {
            get {
                return ResourceManager.GetString("captionNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string captionPassword {
            get {
                return ResourceManager.GetString("captionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        public static string captionPasswordConfirm {
            get {
                return ResourceManager.GetString("captionPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ud. ha modificado su correo electrónico. Por medidas de seguridad deberá volver a hacer login en la aplicación. {0} ¿Desea continuar?.
        /// </summary>
        public static string confirmMessageCambioEmail {
            get {
                return ResourceManager.GetString("confirmMessageCambioEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;img src=&quot;cid:Logo-BiaPlus&quot; width=&quot;80&quot; /&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;&lt;h1&gt;{0}&lt;/h1&gt;&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot; style=&quot;align-content:center; text-align:center;&quot;&gt;
        ///                &lt;h2&gt;{1}&lt;/h2&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot;&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContenidoEmailHTML {
            get {
                return ResourceManager.GetString("ContenidoEmailHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado/a {1}. {0} {0} Este correo le ha sido enviado por la actualizacion de datos que acaba de realizar a su perfil. {0} Los datos han sido actualizados a: {0} Nombre: {1}. {0} Correo Electrónico: {2}. Contraseña: {3}. Si Ud. no ha realizado esta operación comuníquese de manera inmediata con Soporte Técnico y reporte el incidente..
        /// </summary>
        public static string ContenidoEmailTexto {
            get {
                return ResourceManager.GetString("ContenidoEmailTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de {0}.
        /// </summary>
        public static string titlePanel {
            get {
                return ResourceManager.GetString("titlePanel", resourceCulture);
            }
        }
    }
}
