//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PMIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.PMIResource", typeof(PMIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string captionDescripcion {
            get {
                return ResourceManager.GetString("captionDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración (Horas).
        /// </summary>
        public static string captionDuracion {
            get {
                return ResourceManager.GetString("captionDuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha del Incidente.
        /// </summary>
        public static string captionFechaIncidente {
            get {
                return ResourceManager.GetString("captionFechaIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuente.
        /// </summary>
        public static string captionFuenteIncidente {
            get {
                return ResourceManager.GetString("captionFuenteIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización de Incidentes.
        /// </summary>
        public static string captionHeaderFormIncidentes {
            get {
                return ResourceManager.GetString("captionHeaderFormIncidentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar del Incidente.
        /// </summary>
        public static string captionLugarIncidente {
            get {
                return ResourceManager.GetString("captionLugarIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Incidentes.
        /// </summary>
        public static string captionModulo {
            get {
                return ResourceManager.GetString("captionModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturaleza.
        /// </summary>
        public static string captionNaturalezaIncidente {
            get {
                return ResourceManager.GetString("captionNaturalezaIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quién reportó?.
        /// </summary>
        public static string captionNombreReportero {
            get {
                return ResourceManager.GetString("captionNombreReportero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solucionadores.
        /// </summary>
        public static string captionNombreSolucionador {
            get {
                return ResourceManager.GetString("captionNombreSolucionador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        public static string captionObservacion {
            get {
                return ResourceManager.GetString("captionObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Incidente.
        /// </summary>
        public static string captionTipoIncidente {
            get {
                return ResourceManager.GetString("captionTipoIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Realmente desea eliminar el incidente?.
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidentes experimentados.
        /// </summary>
        public static string GridTitle {
            get {
                return ResourceManager.GetString("GridTitle", resourceCulture);
            }
        }
    }
}
