//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProcedimientoBIAResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcedimientoBIAResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.ProcedimientoBIAResource", typeof(ProcedimientoBIAResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está mi Empresa preparada para soportar las consecuencias económicas de una interrupción en los procesos críticos del Negocio?.
        /// </summary>
        public static string Lista1Elemento1 {
            get {
                return ResourceManager.GetString("Lista1Elemento1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué tan eficiente es el comportamiento y anticipación de mi Empresa frente a un desastre?.
        /// </summary>
        public static string Lista1Elemento2 {
            get {
                return ResourceManager.GetString("Lista1Elemento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Puedo reducir el impacto económico de una interrupción del Negocio y garantizar las operaciones necesarias, para cumplir con el funcionamiento normal de la Empresa?.
        /// </summary>
        public static string Lista1Elemento3 {
            get {
                return ResourceManager.GetString("Lista1Elemento3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entradas y Salidas, Proveedores, Interdependencias, Clientes y Productos..
        /// </summary>
        public static string Lista2Elemento1 {
            get {
                return ResourceManager.GetString("Lista2Elemento1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Períodos de Grandes Impactos para el Proceso..
        /// </summary>
        public static string Lista2Elemento10 {
            get {
                return ResourceManager.GetString("Lista2Elemento10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicaciones y/o Plataformas que soportan al Proceso..
        /// </summary>
        public static string Lista2Elemento2 {
            get {
                return ResourceManager.GetString("Lista2Elemento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentación y/o Información..
        /// </summary>
        public static string Lista2Elemento3 {
            get {
                return ResourceManager.GetString("Lista2Elemento3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Clave que interviene en la ejecución del Proceso..
        /// </summary>
        public static string Lista2Elemento4 {
            get {
                return ResourceManager.GetString("Lista2Elemento4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impactos Financiero y Operacional..
        /// </summary>
        public static string Lista2Elemento5 {
            get {
                return ResourceManager.GetString("Lista2Elemento5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amenazas y/o  Riesgos con sus causas, controles, probabilidades, severidad, fuente y estado relacionados con el Proceso..
        /// </summary>
        public static string Lista2Elemento6 {
            get {
                return ResourceManager.GetString("Lista2Elemento6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables: MTD, RTO, RPO y WRT asociadas al Proceso..
        /// </summary>
        public static string Lista2Elemento7 {
            get {
                return ResourceManager.GetString("Lista2Elemento7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesos Alternos..
        /// </summary>
        public static string Lista2Elemento8 {
            get {
                return ResourceManager.GetString("Lista2Elemento8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respaldo de la Información y Sitios de Respaldo Externos..
        /// </summary>
        public static string Lista2Elemento9 {
            get {
                return ResourceManager.GetString("Lista2Elemento9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIA / AIN: Análisis de Impacto al Negocio.
        /// </summary>
        public static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las empresas están rodeadas de amenazas y cuando se ven afectadas por un imprevisto para el que no están preparadas, pueden verse forzadas a interrumpir sus actividades parcial o totalmente..
        /// </summary>
        public static string Parrafo1 {
            get {
                return ResourceManager.GetString("Parrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En éste caso es necesario disponer de las herramientas que le permitan retornar a la situación normal, disminuyendo el impacto del hecho y reduciendo las pérdidas en la medida de lo posible..
        /// </summary>
        public static string Parrafo2 {
            get {
                return ResourceManager.GetString("Parrafo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ante todo esto, debemos responder a las siguientes interrogantes:.
        /// </summary>
        public static string Parrafo3 {
            get {
                return ResourceManager.GetString("Parrafo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Continuidad de la Empresa es vital para el éxito duradero del Negocio, en el mundo de hoy, todos los aspectos de funcionamiento de una Empresa son vulnerables a interrupciones y riesgos..
        /// </summary>
        public static string Parrafo4 {
            get {
                return ResourceManager.GetString("Parrafo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por todo lo antes expuesto, es importante y necesario que las Empresas, realicen un Análisis de Impacto, cuyo alcance contemple recabar información, documentación, así como la elaboración de matrices de impacto e información, que deben ser tomadas en cuenta para realizar eficazmente el Plan de Continuidad del Negocio..
        /// </summary>
        public static string Parrafo5 {
            get {
                return ResourceManager.GetString("Parrafo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En orden de levantar y organizar toda la documentación relacionada con los procesos críticos, conjuntamente con la elaboración de matrices de impacto e información, tanto a nivel corporativo como para las unidades de negocios seleccionadas..
        /// </summary>
        public static string Parrafo6 {
            get {
                return ResourceManager.GetString("Parrafo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La técnica más eficaz para recopilar e intercambiar la información para este Análisis, es a través de la utilización de los métodos de cuestionarios y de la realización de entrevistas al personal de las distintas áreas fundamentales y críticas del negocio. Técnicas de validación y revisión de información, serán utilizadas posteriormente en el proceso de recopilación de información crítica y vital. Los datos obtenidos conjuntamente con la data histórica de continuidad que la Organización posee actualmente, s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Parrafo7 {
            get {
                return ResourceManager.GetString("Parrafo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información por cada Proceso se refiere a:.
        /// </summary>
        public static string Parrafo8 {
            get {
                return ResourceManager.GetString("Parrafo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una vez recopilada toda la información de los procesos fundamentales del Negocio, se analizan y se determinan cuales son los Procesos Críticos del Negocio, a los cuales se les desarrollarán los Procedimientos de Continuidad a utilizar en un caso de desastre para así poder garantizar la continuidad de las operaciones críticas del Negocio..
        /// </summary>
        public static string Parrafo9 {
            get {
                return ResourceManager.GetString("Parrafo9", resourceCulture);
            }
        }
    }
}
