//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReporteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReporteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BcmWeb_30.App_LocalResources.ReporteResource", typeof(ReporteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se tiene planificada alguna acción y/o la acción planificada no mitigará el riesgo.
        /// </summary>
        public static string captionAccion1 {
            get {
                return ResourceManager.GetString("captionAccion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se consideran acciones a largo plazo.
        /// </summary>
        public static string captionAccion2 {
            get {
                return ResourceManager.GetString("captionAccion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones de mitigación se estarán aplicando a corto plazo.
        /// </summary>
        public static string captionAccion3 {
            get {
                return ResourceManager.GetString("captionAccion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones a tomar.
        /// </summary>
        public static string captionAccionTomar {
            get {
                return ResourceManager.GetString("captionAccionTomar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amenaza.
        /// </summary>
        public static string captionAmenaza {
            get {
                return ResourceManager.GetString("captionAmenaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string captionCantidad {
            get {
                return ResourceManager.GetString("captionCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string captionControl {
            get {
                return ResourceManager.GetString("captionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escala.
        /// </summary>
        public static string captionDescEscala {
            get {
                return ResourceManager.GetString("captionDescEscala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string captionDescripcion {
            get {
                return ResourceManager.GetString("captionDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuente de la Amenaza.
        /// </summary>
        public static string captionDescripcionFuente {
            get {
                return ResourceManager.GetString("captionDescripcionFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma: Valoración de “P” + Valoración de “I”  + Valoración de “C” =.
        /// </summary>
        public static string captionDeterminacionEstado {
            get {
                return ResourceManager.GetString("captionDeterminacionEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si la Suma es igual o mayor que “6”.
        /// </summary>
        public static string CaptionDeterminacionLinea1 {
            get {
                return ResourceManager.GetString("CaptionDeterminacionLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si la Suma es “4” o “5”.
        /// </summary>
        public static string CaptionDeterminacionLinea2 {
            get {
                return ResourceManager.GetString("CaptionDeterminacionLinea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si la Suma es “3”.
        /// </summary>
        public static string CaptionDeterminacionLinea3 {
            get {
                return ResourceManager.GetString("CaptionDeterminacionLinea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escala.
        /// </summary>
        public static string captionEscala {
            get {
                return ResourceManager.GetString("captionEscala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string captionEstado {
            get {
                return ResourceManager.GetString("captionEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determinación del Estado.
        /// </summary>
        public static string captionEstadoRiesgo {
            get {
                return ResourceManager.GetString("captionEstadoRiesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento Disparador.
        /// </summary>
        public static string captionEvento {
            get {
                return ResourceManager.GetString("captionEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impacto Operacional.
        /// </summary>
        public static string captionImpactoOperacional {
            get {
                return ResourceManager.GetString("captionImpactoOperacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Implantado.
        /// </summary>
        public static string captionImplantado {
            get {
                return ResourceManager.GetString("captionImplantado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control a Implantar.
        /// </summary>
        public static string captionImplantar {
            get {
                return ResourceManager.GetString("captionImplantar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        public static string captionM01 {
            get {
                return ResourceManager.GetString("captionM01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero.
        /// </summary>
        public static string captionM02 {
            get {
                return ResourceManager.GetString("captionM02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        public static string captionM03 {
            get {
                return ResourceManager.GetString("captionM03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string captionM04 {
            get {
                return ResourceManager.GetString("captionM04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        public static string captionM05 {
            get {
                return ResourceManager.GetString("captionM05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junio.
        /// </summary>
        public static string captionM06 {
            get {
                return ResourceManager.GetString("captionM06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        public static string captionM07 {
            get {
                return ResourceManager.GetString("captionM07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string captionM08 {
            get {
                return ResourceManager.GetString("captionM08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre.
        /// </summary>
        public static string captionM09 {
            get {
                return ResourceManager.GetString("captionM09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octubre.
        /// </summary>
        public static string captionM10 {
            get {
                return ResourceManager.GetString("captionM10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        public static string captionM11 {
            get {
                return ResourceManager.GetString("captionM11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diciembre.
        /// </summary>
        public static string captionM12 {
            get {
                return ResourceManager.GetString("captionM12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMC.
        /// </summary>
        public static string captionMDTHeader {
            get {
                return ResourceManager.GetString("captionMDTHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajo (1).
        /// </summary>
        public static string captionNivelImpacto1 {
            get {
                return ResourceManager.GetString("captionNivelImpacto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio (2).
        /// </summary>
        public static string captionNivelImpacto2 {
            get {
                return ResourceManager.GetString("captionNivelImpacto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto (3).
        /// </summary>
        public static string captionNivelImpacto3 {
            get {
                return ResourceManager.GetString("captionNivelImpacto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baja (1).
        /// </summary>
        public static string captionProbabilidad1 {
            get {
                return ResourceManager.GetString("captionProbabilidad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media (2).
        /// </summary>
        public static string captionProbabilidad2 {
            get {
                return ResourceManager.GetString("captionProbabilidad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta (3).
        /// </summary>
        public static string captionProbabilidad3 {
            get {
                return ResourceManager.GetString("captionProbabilidad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso.
        /// </summary>
        public static string captionProceso {
            get {
                return ResourceManager.GetString("captionProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POR.
        /// </summary>
        public static string captionRPOHeader {
            get {
                return ResourceManager.GetString("captionRPOHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOR.
        /// </summary>
        public static string captionRTOHeader {
            get {
                return ResourceManager.GetString("captionRTOHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severidad.
        /// </summary>
        public static string captionSeveridad {
            get {
                return ResourceManager.GetString("captionSeveridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Organizativa.
        /// </summary>
        public static string captionUnidad {
            get {
                return ResourceManager.GetString("captionUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoración.
        /// </summary>
        public static string captionValoracion {
            get {
                return ResourceManager.GetString("captionValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string captionValoracionFuente {
            get {
                return ResourceManager.GetString("captionValoracionFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de Escala.
        /// </summary>
        public static string captionValorEscala {
            get {
                return ResourceManager.GetString("captionValorEscala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de Impacto.
        /// </summary>
        public static string captionVIHeader {
            get {
                return ResourceManager.GetString("captionVIHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRT.
        /// </summary>
        public static string captionWRTHeader {
            get {
                return ResourceManager.GetString("captionWRTHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel del Impacto (I).
        /// </summary>
        public static string SubtituloNivelImpacto {
            get {
                return ResourceManager.GetString("SubtituloNivelImpacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toda la información que se muestra en los gráficos se corresponde a la última información actualizada o al último año. No existe información histórica..
        /// </summary>
        public static string TextoExplicativoInformacion {
            get {
                return ResourceManager.GetString("TextoExplicativoInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla: Acciones a tomar dependiendo de la Valoración del Riesgo.
        /// </summary>
        public static string TituloAcciones {
            get {
                return ResourceManager.GetString("TituloAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control (C) sobre el Riesgo.
        /// </summary>
        public static string TituloControl {
            get {
                return ResourceManager.GetString("TituloControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla: Fuentes de la Amenaza.
        /// </summary>
        public static string TituloFuentes {
            get {
                return ResourceManager.GetString("TituloFuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Características del Impacto (I).
        /// </summary>
        public static string TituloImpacto {
            get {
                return ResourceManager.GetString("TituloImpacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probabilidad (P) de Ocurrencia.
        /// </summary>
        public static string TituloProbabilidad {
            get {
                return ResourceManager.GetString("TituloProbabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla: Severidad del Riesgo.
        /// </summary>
        public static string TituloSeveridad {
            get {
                return ResourceManager.GetString("TituloSeveridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla: Estado de Eventos por Proceso.
        /// </summary>
        public static string TituloTablaRiesgoControl {
            get {
                return ResourceManager.GetString("TituloTablaRiesgoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablas: Valoración del Riesgo.
        /// </summary>
        public static string TituloTablasValoracionRiesgo {
            get {
                return ResourceManager.GetString("TituloTablasValoracionRiesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla: Valoración del Estado de Riesto.
        /// </summary>
        public static string TituloValoracionRiesgo {
            get {
                return ResourceManager.GetString("TituloValoracionRiesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir el gráfico.
        /// </summary>
        public static string ToolTipPrintButton {
            get {
                return ResourceManager.GetString("ToolTipPrintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar el gráfico y guardar en su PC.
        /// </summary>
        public static string ToolTipSaveToDiskButton {
            get {
                return ResourceManager.GetString("ToolTipSaveToDiskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar el gráfico a una nueva ventana.
        /// </summary>
        public static string ToolTipSaveToWindowButton {
            get {
                return ResourceManager.GetString("ToolTipSaveToWindowButton", resourceCulture);
            }
        }
    }
}
